server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: xmlynek
    password: password
    url: jdbc:postgresql://postgres:5432/notification
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  rabbitmq:
    addresses: rabbitmq:5672
    password: password
    username: filip
  zipkin:
    base-url: http://zipkin:9411


rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
eureka:
  client:
    enabled: false
